-- PostgreSQL bootstrap schema draft for the Rust platform.
-- This file mirrors the current SQLite schema without enabling PostgreSQL runtime.

create table if not exists setup_state (
  key text primary key,
  value integer not null,
  updated_at text not null
);

create table if not exists setup_runs (
  id text primary key,
  status text not null,
  reason text,
  created_at text not null,
  updated_at text not null
);

create table if not exists setup_step_logs (
  id integer generated by default as identity primary key,
  run_id text not null references setup_runs(id) on delete cascade,
  step_key text not null,
  status text not null,
  message text not null,
  created_at text not null
);

create table if not exists iam_organizations (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  scope text not null check (scope in ('platform', 'tenant', 'product')),
  status text not null,
  created_at text not null,
  updated_at text not null,
  deleted_at text
);

create table if not exists iam_users (
  id integer generated by default as identity primary key,
  email text not null unique,
  display_name text not null,
  password_hash text not null,
  status text not null,
  email_verified_at text,
  created_at text not null,
  updated_at text not null,
  deleted_at text
);

create table if not exists iam_roles (
  id integer generated by default as identity primary key,
  org_id integer references iam_organizations(id) on delete cascade,
  code text not null,
  name text not null,
  scope text not null check (scope in ('platform', 'tenant', 'product')),
  system_builtin integer not null default 0,
  created_at text not null,
  updated_at text not null,
  unique(org_id, code)
);

create table if not exists iam_permissions (
  id integer generated by default as identity primary key,
  product_code text not null,
  scope text not null check (scope in ('platform', 'tenant', 'product')),
  code text not null,
  name text not null,
  created_at text not null,
  unique(product_code, scope, code)
);

create table if not exists iam_role_permissions (
  role_id integer not null references iam_roles(id) on delete cascade,
  permission_id integer not null references iam_permissions(id) on delete cascade,
  primary key(role_id, permission_id)
);

create table if not exists iam_memberships (
  id integer generated by default as identity primary key,
  org_id integer references iam_organizations(id) on delete cascade,
  user_id integer not null references iam_users(id) on delete cascade,
  role_code text not null,
  status text not null,
  created_at text not null,
  updated_at text not null,
  unique(org_id, user_id, role_code)
);

create table if not exists iam_sessions (
  id text primary key,
  session_token_hash text not null unique,
  refresh_token_hash text unique,
  user_id integer not null references iam_users(id) on delete cascade,
  org_id integer not null references iam_organizations(id) on delete cascade,
  product_code text not null,
  client_type text not null,
  status text not null,
  expires_at text not null,
  refresh_expires_at text,
  revoked_at text,
  created_at text not null,
  updated_at text not null
);

create table if not exists iam_api_tokens (
  id integer generated by default as identity primary key,
  org_id integer not null references iam_organizations(id) on delete cascade,
  user_id integer not null references iam_users(id) on delete cascade,
  token_hash text not null unique,
  token_prefix text not null,
  status text not null,
  expires_at text,
  created_at text not null,
  revoked_at text
);

create table if not exists iam_invitations (
  id integer generated by default as identity primary key,
  org_id integer not null references iam_organizations(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  role_code text not null default 'owner',
  status text not null,
  expires_at text not null,
  created_at text not null,
  accepted_at text,
  revoked_at text
);

create table if not exists iam_password_resets (
  id integer generated by default as identity primary key,
  user_id integer not null references iam_users(id) on delete cascade,
  token_hash text not null unique,
  status text not null,
  expires_at text not null,
  created_at text not null,
  used_at text
);

create table if not exists iam_email_verifications (
  id integer generated by default as identity primary key,
  user_id integer not null references iam_users(id) on delete cascade,
  email text not null,
  token_hash text not null unique,
  status text not null,
  expires_at text not null,
  created_at text not null,
  verified_at text
);

create table if not exists iam_mfa_factors (
  id integer generated by default as identity primary key,
  user_id integer not null references iam_users(id) on delete cascade,
  kind text not null,
  secret_ciphertext text not null,
  status text not null,
  created_at text not null,
  verified_at text,
  revoked_at text
);

create table if not exists iam_mfa_recovery_codes (
  id integer generated by default as identity primary key,
  user_id integer not null references iam_users(id) on delete cascade,
  code_hash text not null unique,
  code_prefix text not null,
  status text not null check (status in ('active', 'used', 'revoked')),
  created_at text not null,
  used_at text,
  revoked_at text
);

create table if not exists iam_audit_logs (
  id integer generated by default as identity primary key,
  org_id integer references iam_organizations(id) on delete set null,
  user_id integer references iam_users(id) on delete set null,
  action text not null,
  scope text not null,
  product_code text not null,
  detail text not null,
  created_at text not null
);

create table if not exists iam_notification_outbox (
  id integer generated by default as identity primary key,
  org_id integer references iam_organizations(id) on delete set null,
  user_id integer references iam_users(id) on delete set null,
  product_code text not null,
  channel text not null,
  template_code text not null,
  recipient text not null,
  related_kind text not null,
  related_id integer not null,
  payload_json text not null,
  status text not null check (status in ('pending', 'delivered', 'failed', 'cancelled')),
  attempt_count integer not null default 0,
  available_at text not null,
  created_at text not null,
  locked_at text,
  delivered_at text,
  failed_at text,
  failure_reason text
);

create table if not exists iam_notification_delivery_secrets (
  id integer generated by default as identity primary key,
  outbox_id integer not null unique references iam_notification_outbox(id) on delete cascade,
  secret_kind text not null check (secret_kind in ('raw_token')),
  secret_ciphertext text,
  status text not null check (status in ('pending', 'purged')),
  created_at text not null,
  purged_at text
);

create table if not exists system_apis (
  id text not null,
  method text not null,
  path text not null,
  tag text not null,
  summary text not null,
  access text not null,
  permission text,
  scope text not null,
  product_code text not null,
  created_at text not null,
  updated_at text not null,
  primary key(method, path)
);

create table if not exists system_menus (
  id integer generated by default as identity primary key,
  code text not null unique,
  title text not null,
  path text not null,
  permission text,
  scope text not null,
  sort_order integer not null default 0,
  created_at text not null
);

create table if not exists system_configs (
  key text primary key,
  value_json text not null,
  updated_at text not null
);

create table if not exists system_dictionaries (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  created_at text not null,
  deleted_at text
);

create table if not exists system_parameters (
  id integer generated by default as identity primary key,
  key text not null unique,
  name text not null,
  value text not null,
  created_at text not null,
  updated_at text not null,
  deleted_at text
);

create table if not exists system_operation_records (
  id integer generated by default as identity primary key,
  actor_user_id integer,
  method text not null,
  path text not null,
  status integer not null,
  created_at text not null
);

create table if not exists system_server_metrics (
  id integer generated by default as identity primary key,
  source text not null,
  payload_json text not null,
  collected_at text not null
);

create table if not exists system_version_packages (
  id integer generated by default as identity primary key,
  version_name text not null,
  version_code text not null,
  manifest_json text not null,
  status text not null default 'draft',
  created_at text not null,
  published_at text,
  retired_at text,
  deleted_at text
);

create table if not exists system_version_release_events (
  id integer generated by default as identity primary key,
  package_id integer not null references system_version_packages(id),
  previous_active_id integer references system_version_packages(id),
  action text not null,
  status text not null,
  reason text,
  created_at text not null
);

create table if not exists system_media_assets (
  id integer generated by default as identity primary key,
  category text,
  display_name text not null,
  storage_key text not null,
  mime_type text not null,
  size_bytes bigint not null,
  created_at text not null,
  deleted_at text
);

create table if not exists system_traffic_probe_targets (
  id integer generated by default as identity primary key,
  name text not null,
  url text not null,
  expected_status integer not null,
  status text not null,
  created_at text not null,
  deleted_at text
);

create table if not exists system_traffic_probe_results (
  id integer generated by default as identity primary key,
  target_id integer not null references system_traffic_probe_targets(id) on delete cascade,
  status text not null,
  detail_json text not null,
  probed_at text not null
);

create table if not exists system_traffic_probe_alerts (
  id integer generated by default as identity primary key,
  target_id integer not null references system_traffic_probe_targets(id) on delete cascade,
  result_id integer not null unique references system_traffic_probe_results(id) on delete cascade,
  severity text not null check (severity in ('warning', 'critical')),
  status text not null check (status in ('open', 'acknowledged', 'resolved')),
  reason text not null,
  detail_json text not null,
  opened_at text not null,
  acknowledged_at text,
  resolved_at text
);

create index if not exists idx_iam_sessions_refresh_token_hash on iam_sessions(refresh_token_hash);
create index if not exists idx_iam_invitations_token_hash on iam_invitations(token_hash);
create index if not exists idx_iam_mfa_recovery_codes_user_status on iam_mfa_recovery_codes(user_id, status);
create index if not exists idx_iam_notification_outbox_status on iam_notification_outbox(status, available_at);
create index if not exists idx_iam_notification_outbox_related on iam_notification_outbox(related_kind, related_id);
create index if not exists idx_iam_notification_outbox_retry on iam_notification_outbox(status, available_at, attempt_count);
create index if not exists idx_iam_notification_delivery_secrets_outbox on iam_notification_delivery_secrets(outbox_id, status);
create index if not exists idx_system_traffic_probe_alerts_status on system_traffic_probe_alerts(status, opened_at);
create index if not exists idx_system_traffic_probe_alerts_target on system_traffic_probe_alerts(target_id, status);
create index if not exists idx_system_version_release_events_package_id on system_version_release_events(package_id);
