import type { BlogPost } from "./posts";

// Generated by scripts/generate-blog-posts.mjs. Do not edit by hand.
export const generatedBlogPosts = [
  {
    "author": "Aoi Team",
    "cover": "/images/blog/react-frontend-migration.svg",
    "date": "2026-06-18",
    "description": "Notes on the first phase of moving Aoi from a Nuxt admin console to a unified React public site and SaaS admin.",
    "draft": false,
    "locale": "en",
    "slug": "react-frontend-migration",
    "tags": [
      "React",
      "i18n",
      "Design System"
    ],
    "title": "React Frontend Migration Phase One",
    "updatedAt": "2026-06-18",
    "content": "Phase one creates the React project foundation instead of deleting the legacy Nuxt admin immediately. This keeps the migration evidence-based while the build output, Go static hosting path, and `/admin` route behavior are verified.\n\n## Phase goals\n\n- Create the React Router Framework SPA.\n- Establish the Aoi React component layers.\n- Add i18next resources and `X-Locale` mapping.\n- Validate Markdown front matter.\n\nEach migrated admin page must also remove the matching old route, component, API call, and obsolete i18n keys in the same phase.",
    "highlightedCode": {},
    "path": "content/blog/en/react-frontend-migration.md"
  },
  {
    "author": "Aoi Team",
    "cover": "/images/blog/react-frontend-migration.svg",
    "date": "2026-06-18",
    "description": "记录 Aoi 从 Nuxt 后台迁移到 React 官网与 SaaS 后台一体化前端的第一阶段边界。",
    "draft": false,
    "locale": "zh-CN",
    "slug": "react-frontend-migration",
    "tags": [
      "React",
      "i18n",
      "Design System"
    ],
    "title": "React 前端迁移第一阶段",
    "updatedAt": "2026-06-18",
    "content": "第一阶段先建立新的 React 工程骨架，而不是直接删除旧的 Nuxt 后台。这样可以在验证构建产物、Go 静态托管路径和 `/admin` 路由守卫前，保留足够的事实依据。\n\n## 本阶段目标\n\n- 建立 React Router Framework SPA。\n- 建立 Aoi React 组件分层。\n- 建立 i18next 资源与 `X-Locale` 映射。\n- 建立 Markdown front matter 校验。\n\n后续每迁移一个后台页面，都需要同步清理旧入口、旧组件、旧 API 调用和废弃 i18n key。",
    "highlightedCode": {},
    "path": "content/blog/zh-CN/react-frontend-migration.md"
  }
] satisfies BlogPost[];
