import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  layout("./routes/public/layout.tsx", [
    index("./routes/public/home.tsx"),
    route("about", "./routes/public/about.tsx"),
    route("blog", "./routes/public/blog-index.tsx"),
    route("blog/:slug", "./routes/public/blog-detail.tsx"),
    route("terms", "./routes/public/terms.tsx"),
    route("privacy", "./routes/public/privacy.tsx"),
    route("login", "./routes/auth/login.tsx"),
    route("signup", "./routes/auth/signup.tsx"),
    route("signup/verify/:token", "./routes/auth/signup-verify.tsx"),
    route("password/forgot", "./routes/auth/password-forgot.tsx"),
    route("password/reset", "./routes/auth/password-reset.tsx"),
    route("invitations", "./routes/auth/invitation-index.tsx"),
    route("invitations/:token", "./routes/auth/invitation.tsx"),
  ]),
  route("setup", "./routes/setup/layout.tsx", [
    index("./routes/setup/index.tsx"),
    route(":step", "./routes/setup/step.tsx"),
  ]),
  route("admin", "./routes/admin/layout.tsx", [
    index("./routes/admin/dashboard.tsx"),
    route("iam", "./routes/admin/iam.tsx"),
    route("organizations", "./routes/admin/organizations.tsx"),
    route("users", "./routes/admin/users.tsx"),
    route("roles", "./routes/admin/roles.tsx"),
    route("sessions", "./routes/admin/sessions.tsx"),
    route("security", "./routes/admin/security.tsx"),
    route("traffic-hijack", "./routes/admin/traffic-hijack.tsx"),
    route("api-tokens", "./routes/admin/api-tokens.tsx"),
    route("probes", "./routes/admin/probes.tsx"),
    route("apis", "./routes/admin/apis.tsx"),
    route("menus", "./routes/admin/menus.tsx"),
    route("dictionaries", "./routes/admin/dictionaries.tsx"),
    route("system", "./routes/admin/system.tsx"),
    route("design-system", "./routes/admin/design-system.tsx"),
    route("parameters", "./routes/admin/parameters.tsx"),
    route("operation-records", "./routes/admin/operation-records.tsx"),
    route("audit-logs", "./routes/admin/audit-logs.tsx"),
    route("login-logs", "./routes/admin/login-logs.tsx"),
    route("error-logs", "./routes/admin/error-logs.tsx"),
    route("media", "./routes/admin/media.tsx"),
    route("media/resumable", "./routes/admin/media-resumable.tsx"),
    route("plugins", "./routes/admin/plugins.tsx"),
    route("versions", "./routes/admin/versions.tsx"),
    route("*", "./routes/admin/not-found.tsx"),
  ]),
  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
